### PR TITLE
Read pattern and partition_by attributes from object group

### PR DESCRIPTION
**Pull request by benzaita**

### CODE REVIEW

**Comment by kzonov** [comment]
I'll need a proper walkthrough on the WHY of these changes. They look sane, but for the start I don't understand two things:
1. Why we previously were using these values and setting them but not reading them?
2. I see here https://github.com/benzaita/terraform-provider-chaossearch/pull/5/files#diff-a952afb664ead726ae4bd2d464aeefda08f4ea60c9c5c046f6b399f60815da0aR160 you added the `partition_by` field, but not the `pattern` one
3. Do I understand correctly, CS has both JSON and XML endpoints? o_O

**Comment by benzaita** [comment]
@graffzon I'll start with the easiest:

> 3. Do I understand correctly, CS has both JSON and XML endpoints? o_O

Yes. Some endpoints mimic (or are compatible?) with AWS S3 and thus return XML. Others are more "RESTy" and return JSON. And then there are the ElasticSearch-compatible APIs as well :-)

> 2. I see here https://github.com/benzaita/terraform-provider-chaossearch/pull/5/files#diff-a952afb664ead726ae4bd2d464aeefda08f4ea60c9c5c046f6b399f60815da0aR160 you added the `partition_by` field, but not the `pattern` one

That's probably a mistake. Both fields, when returned from the API should be written into the TF state. See the task below.

> 1. Why we previously were using these values and setting them but not reading them?

So when Terraform _reads_ resource (when importing a resource or when refreshing it AFAIK) TF invokes the `ReadObjectGroup` function. That one uses the client to read the object group's attributes from the API and writes the information to the TF state (well, an output parameter to be precise). The `ReadObjectGroup` was not reading the `pattern` and `partition_by` attributes and not writing them to the TF state: 

 - it didn't read `pattern` because we did not use it at the time.
 - it didn't read `partition_by` because I didn't know which API returns it (it does not appear in the bucket tagging).

I hope it's clear now.

- [x] Write `pattern` attribute to TF state when reading resource

**Comment by kzonov** [comment]
> Some endpoints mimic (or are compatible?) with AWS S3 and thus return XML. Others are more "RESTy" and return JSON. And then there are the ElasticSearch-compatible APIs as well :-)

Great effort for being compatible xD
I'll give it another look, considering your comments

**Review by kzonov — APPROVED** [review]
Now things make more sense for me, so except the fix mentioned before, it looks good

**Pull request merged**
